services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=MySqlPass@word
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
